## Numpy

Numpy is a library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays (e.g. linear algebra, random number generation, etc.). It is the fundamental package for scientific computing with Python.

#### Basic Initialization

In [5]:
pip install numpy --upgrade --quiet

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

#### Basic Operations

In [9]:
# 1. Create an array of 10 zeros
arr1 = np.zeros(10)
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
# 2. Create an array of 10 fives
arr2 = np.ones(10) * 5
print(arr2)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [11]:
# 3. Create an array of multiples of 5 from 5 to 50
arr3 = np.arange(5, 51, 5)
print(arr3)

[ 5 10 15 20 25 30 35 40 45 50]


In [14]:
# 4. Create an array of x values from 0 to 10, where x is the square of the index  
arr4 = np.arange(0, 11) ** 2
print(arr4)

[  0   1   4   9  16  25  36  49  64  81 100]


In [15]:
# 5. Create an array with 20 linearly spaced points between 0 and 1
arr5 = np.linspace(0, 1, 20)
print(arr5)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [19]:
# 6. Create a 3x3 matrix with values ranging from 0 to 8
arr6 = np.arange(0, 9).reshape(3, 3)
print(arr6)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
# 7. Create a 3x3 identity matrix
arr7 = np.eye(3)
print(arr7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
# 8. Use NumPy to generate a random number between 0 and 1
arr8 = np.random.rand(1)
print(arr8)

[0.44384251]


In [22]:
# 9. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
arr9 = np.random.randn(25)
print(arr9)

[ 0.98741533  1.92878648 -1.62596162 -0.67543627 -0.27889234  1.06591622
 -0.12111595 -0.47178997 -1.18135714  0.58063865  1.36794151 -0.03908597
 -0.64148021  1.33409617  0.56649069 -1.27855707 -0.52623817 -0.45146149
  0.45278266  0.83908284  0.9274258  -0.65971299  1.5354619  -0.47591723
 -0.36441188]


In [24]:
# 10. Create the following matrix:
arr10 = np.arange(0.01, 1.01, 0.01).reshape(10, 10)
print(arr10)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [25]:
# 11. Create an array of 20 linearly spaced points between 0 and 1:
arr11 = np.linspace(0, 1, 20)
print(arr11)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [17]:
# 12. Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:
arr12 = np.arange(1, 26).reshape(5, 5)
print(arr12)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [27]:
# 13. Get the sum of all the values in mat
arr13 = np.sum(arr12)
print(arr13)

325


In [28]:
# 14. Get the standard deviation of the values in mat
arr14 = np.std(arr12)
print(arr14)

7.211102550927978


In [29]:
# 15. Get the sum of all the columns in mat
arr15 = np.sum(arr12, axis=0)
print(arr15)

[55 60 65 70 75]


In [18]:
# 16. Slice the first 3 rows of mat
arr16 = arr12[:3]
print(arr16)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [20]:
# 17. Slice the range of rows from 2 to 4
arr17 = arr12[1:4]
print(arr17)

[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


#### File

In [33]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x29ee9188990>)

In [9]:
import numpy as np
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [15]:
weights = np.array([0.3, 0.2, 0.5])
yields = climate_data @ weights
climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

#### 